# Render service spec for this Next.js app
services:
  - type: web
    name: iemrfsite1
    env: node
    plan: starter
    region: oregon
    
    # Use npm to match the existing package-lock.json in this repo
    buildCommand: |
      npm ci
      npm run build

    startCommand: npm run start
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
    
    autoDeploy: true
    pullRequestPreviews: false
    branch: main
    healthCheckPath: /

    # Auto-deploy settings
    autoDeploy: true
    pullRequestPreviews: false

    # Branch settings
    branch: main

    # Advanced settings
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

    # Build filters (optional)
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - next.config.js
        - tsconfig.json
        - tailwind.config.ts
