# Render service spec for this Next.js app
services:
  - type: web
    name: iemrfsite1
    env: node
    plan: starter
    region: oregon

    # Build settings
    buildCommand: |
      npm install -g pnpm@8
      pnpm install
      pnpm build

    # Start command for Next.js
    startCommand: pnpm start

    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PNPM_VERSION
        value: 8.x

    # Health check path
    healthCheckPath: /

    # Auto-deploy settings
    autoDeploy: true
    pullRequestPreviews: false

    # Branch settings
    branch: main

    # Advanced settings
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

    # Build filters (optional)
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - pnpm-lock.yaml
        - next.config.js
        - tsconfig.json
        - tailwind.config.ts
